import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import "./globals.css";
import { Header } from "./components/Header";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Voto Certo",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${interSans.variable} ${geistMono.variable} min-h-screen bg-gray-100 font-sans text-gray-900 antialiased dark:bg-gray-900 dark:text-white`}
      >
        <ThemeInit />
        <Header />
        {children}
      </body>
    </html>
  );
}
