import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import "./globals.css";
import { Header } from "./components/Header";

// Importe seu Header (assumindo que ele está em 'app/components/Header.tsx')

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>

      {/* Movemos as classes de fundo do seu page.tsx para cá,
        para que o fundo se aplique a todo o layout.
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-gray-100 font-sans text-gray-900 antialiased dark:bg-gray-900 dark:text-white`}
      >
        <ThemeInit />

        {/* 🚀 Seu Header é renderizado aqui */}
        <Header />

        {/* O {children} renderizará o conteúdo da página ativa 
          (ex: app/proposicoes/page.tsx ou app/deputados/page.tsx) 
        */}
        {children}

        {/* Você também poderia adicionar um <Footer /> aqui */}
      </body>
    </html>
  );
}
